### ISSUE TITLE
Not generating all tables

### ISSUE THREAD

**Issue by maxresnikoff** [jan-vandenberg/cruddiy#29]
I have 56 tables, and only 27 of them get generated by CRUDDIY.

Observations: 
table.php - Shows all 56 tables to select
columns.php - Shows all 56 tables and their relevant columns
generate.php - Shows only 27 tables
app/index.php - Shows only 27 buttons
directory - Only files for the 27 tables were generated into the directory

I presume there is an issue / limit with the generation of the tables?

**Comment by jan-vandenberg** [comment]
Interesting, could you share maybe the database stucture/layout?

**Comment by jan-vandenberg** [comment]
Hi I tried it myself with a large database with many tables and my Apache error.log says the following:

 AH01071: Got error 'PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.

I assume this is probably also your problem.  Can you check the logs?

Cruddiy could have some better error checking and warnings but it can be fixed in the PHP settings.

**Comment by maxresnikoff** [comment]
I checked and can't see any errors.
I have also checked with the server provider and they didnt find any errors at all. 

They ran through the steps of generating the CRUD pages, and said it all worked fine with no errors, so they believe its a scripting issue, not a server issue/limitation.

**Comment by jan-vandenberg** [comment]
What number did you set the variables too?

**Comment by maxresnikoff** [comment]
max_input_vars = 5000

**Comment by devasia2112** [comment]
I had the same issue a few minutes ago, my solution was to use this PR https://github.com/jan-vandenberg/cruddiy/pull/24/commits/401de56698d5dd91a6e1b1d6c874d8b958f7a70d on top of this `generate.php` file https://github.com/Germain-Italic/cruddiy/blob/ee6b6ca3123c8871b2aaac8172250f7008939759/core/generate.php

In my case only the `index.php` file was not been generated (it was missing like it was interrupted when been writing), but all the rest was fine.

**Comment by jan-vandenberg** [comment]
I am confused as to what is happening here. What prompted you @devasia2112 to use this PR (which has been pulled in before)? Or can you explain why it works then?

**Comment by jan-vandenberg** [comment]
Can you share your generate.php file (that works)?

**Comment by devasia2112** [comment]
@jan-vandenberg 

These are the steps I took:
- git clone the master repo.
- tested first, but the date fields was generating as text fields.
- after reading a few issues, i found this fix https://github.com/jan-vandenberg/cruddiy/commit/bb8e7f2f541b972d52844f4d1812ddbe535a797a  from issue #23 
- I merged with my `generate.php` and it worked.

yes, here is the one working for me: https://gist.github.com/devasia2112/1169866e84862ad11389776b6c97598e

**Comment by jan-vandenberg** [comment]
Thanks. From what I can see your generate.php file has one less post variable (that one was added later) so what you do with the 'fix' is removing this extra variable and this makes it work in your situation. (Note: this variable is the table display name on the Index page, so if you give your table a pretty name it won't show the pretty name on the index page; it will show the actual table name).

I just tested on my side with a database with more 201 tables by editing/updating/setting to

max_input_vars = 100000 

in /etc/php/7.4/fpm/php.ini  

The default is 1000. When it is 1000 the table generation of these 201 tables gets cut off around 20 tables and throws an error (AH01071: Got error 'PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0',)

But when I update the max_input_vars to a ridiculous number (100000) it works as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/13764557/118675048-95ed5c80-b7fa-11eb-9dfd-8aab37d46503.png)

I think this is because the generate page does a bunch of loops etc. I have to see if I can do this part a bit more clever.

**Comment by jan-vandenberg** [comment]
I've added a little bit of error checking. I think that is fine for now. https://github.com/jan-vandenberg/cruddiy/commit/1a99b74f4f443acc50f26a07e4814754b5504d40

**Comment by maxresnikoff** [comment]
> I've added a little bit of error checking. I think that is fine for now. [1a99b74](https://github.com/jan-vandenberg/cruddiy/commit/1a99b74f4f443acc50f26a07e4814754b5504d40)

I shall give it a go tomorrow and see if I get the error output. Thanks for this

**Comment by maxresnikoff** [comment]
I have tested with the latest version (With the new error checking), and still having the same issue. The output at the bottom of generate.php is as follows:

```
Your app has been created! It is completely self contained in the /app folder. You can move this folder anywhere on your server.

Go to your app (this will open your app in a new tab).

You can close this tab or leave it open and use the back button to make changes and regenerate the app. Every run will overwrite the previous app unless you checked the "Keep previously generated startpage" box.

If you need further instructions please visit cruddiy.com
```

**Comment by maxresnikoff** [comment]
I have managed to get it working. Annoyingly, the server provider has it set so php.ini only applies the settings to the directory it is in and none of the others... So i have to create a php.ini for each folder i need things changed in. 

ALTHOUGH, when it was stuck on max_input_vars=3000, the error checking you added didnt seem to make an appearance. 
I: echo ini_get("max_input_vars"); and showed 3000, so not sure if the release 2.2 is missing the error checking, or it just didnt work for some reason. (i tried 3/4 times)

All sorted now! not your fault at all, but that error checking definately didnt work for me i'm afraid!
