### ISSUE TITLE
Small bug when the table does not has "id" column

### ISSUE THREAD

**Issue by eried** [jan-vandenberg/cruddiy#3]
Hi, neat little tool! I was just following some CRUD example to make all this manually for some quick hack I need. I just found out that 1 index file is broken with:

![image](https://user-images.githubusercontent.com/1091420/93087977-9d6fcb00-f699-11ea-8625-ce5f33fdd8dd.png)

And in the .php file itself I can see that:
![image](https://user-images.githubusercontent.com/1091420/93088044-b6787c00-f699-11ea-99ae-0ff1cdbd145f.png)

But that table index is actually `iccid`.

**Comment by jan-vandenberg** [comment]
Have you defined a primary key for your table? Because Cruddiy always uses the primary key for ordering. 

You can tell this from the columns.php page: there will be a key icon next to the field. Like so:
![image](https://user-images.githubusercontent.com/13764557/93104609-61933080-f6ae-11ea-9191-d361659084b4.png)

Or of course, check your database for a primary key. 

It is however a good find, one that I can add to the error checking of Cruddiy to prompt people for their primary key.

**Comment by eried** [comment]
oh, yes maybe you are right. The column was only index as "different". Thanks
